#!/usr/bin/env python3
"""
KPI API Server
Serves KPI data generated by the 24/7 LLM analysis system
"""

import os
import json
from datetime import datetime, timezone
from flask import Flask, jsonify, request
from flask_cors import CORS
from typing import List, Dict, Any

app = Flask(__name__)
CORS(app)

KPI_STORAGE_FILE = 'kpi_history.json'

def load_kpi_history() -> List[Dict[str, Any]]:
    """Load KPI history from file"""
    try:
        with open(KPI_STORAGE_FILE, 'r') as f:
            return json.load(f)
    except FileNotFoundError:
        return []

@app.route('/api/kpi/recent')
def get_recent_kpis():
    """Get recent KPIs"""
    limit = int(request.args.get('limit', 20)) if 'request' in locals() else 20
    kpis = load_kpi_history()
    recent = kpis[-limit:] if kpis else []
    return jsonify({
        'kpis': recent,
        'count': len(recent),
        'timestamp': datetime.now(timezone.utc).isoformat()
    })

@app.route('/api/kpi/latest')
def get_latest_kpis():
    """Get latest KPIs from most recent analysis cycle"""
    kpis = load_kpi_history()
    if not kpis:
        return jsonify({'kpis': [], 'timestamp': datetime.now(timezone.utc).isoformat()})
    
    # Group by timestamp and get the latest group
    from collections import defaultdict
    grouped = defaultdict(list)
    for kpi in kpis:
        grouped[kpi['timestamp']].append(kpi)
    
    latest_timestamp = max(grouped.keys())
    latest_kpis = grouped[latest_timestamp]
    
    return jsonify({
        'kpis': latest_kpis,
        'timestamp': latest_timestamp,
        'count': len(latest_kpis)
    })

@app.route('/api/kpi/categories')
def get_kpi_categories():
    """Get KPIs grouped by category"""
    kpis = load_kpi_history()
    categories = {}
    
    for kpi in kpis:
        category = kpi.get('category', 'unknown')
        if category not in categories:
            categories[category] = []
        categories[category].append(kpi)
    
    return jsonify({
        'categories': categories,
        'count': len(categories)
    })

@app.route('/api/kpi/letter/<letter>')
def get_letter_kpis(letter):
    """Get KPIs for a specific letter"""
    kpis = load_kpi_history()
    letter_kpis = [kpi for kpi in kpis if kpi.get('letter', 'all') == letter.upper()]
    
    return jsonify({
        'letter': letter.upper(),
        'kpis': letter_kpis[-50:],  # Last 50 KPIs for this letter
        'count': len(letter_kpis)
    })

@app.route('/api/kpi/stats')
def get_kpi_stats():
    """Get KPI statistics"""
    kpis = load_kpi_history()
    
    if not kpis:
        return jsonify({
            'total_kpis': 0,
            'categories': {},
            'latest_timestamp': None
        })
    
    # Calculate statistics
    total_kpis = len(kpis)
    categories = {}
    
    for kpi in kpis:
        category = kpi.get('category', 'unknown')
        categories[category] = categories.get(category, 0) + 1
    
    latest_timestamp = kpis[-1]['timestamp'] if kpis else None
    
    return jsonify({
        'total_kpis': total_kpis,
        'categories': categories,
        'latest_timestamp': latest_timestamp,
        'first_timestamp': kpis[0]['timestamp'] if kpis else None
    })

@app.route('/health')
def health():
    """Health check endpoint"""
    return jsonify({'status': 'healthy', 'service': 'kpi-api'})

if __name__ == '__main__':
    port = int(os.getenv('PORT', 8080))
    app.run(host='0.0.0.0', port=port)
