export interface DataSourceSpec {
  id: number;
  name: string;
  category: string;
  sampling_method: string;
  data_sampled: string;
  api_endpoint: string;
  sample_frequency: string;
  data_points_per_sample: string;
  letter_extraction_method: string;
  example_data: string;
  notes: string;
}

export const DATA_SOURCE_SPECS: DataSourceSpec[] = [
  {
    id: 1,
    name: "Solana Token Names",
    category: "Blockchain",
    sampling_method: "API",
    data_sampled: "SPL token names, symbols, and metadata from Solana token list",
    api_endpoint: "https://api.solana.com",
    sample_frequency: "Every 60 seconds",
    data_points_per_sample: "~5,000-50,000 tokens",
    letter_extraction_method: "Extract letters from token names and symbols, count occurrences",
    example_data: "BONK, WIF, RAY, JUP, ORCA, SOL, USDC, USDT",
    notes: "Weights token names by 24h volume and market cap"
  },
  {
    id: 2,
    name: "Solana NFT Collections",
    category: "NFT",
    sampling_method: "API",
    data_sampled: "NFT collection names, metadata, and creator addresses",
    api_endpoint: "https://api.metaplex.com",
    sample_frequency: "Every 5 minutes",
    data_points_per_sample: "~10,000-80,000 collections",
    letter_extraction_method: "Extract letters from collection names and symbols",
    example_data: "Degenerate Ape Academy, Solana Monkey Business, Mad Lads",
    notes: "Includes verified and unverified collections"
  },
  {
    id: 3,
    name: "Solana Domains",
    category: "Blockchain",
    sampling_method: "API",
    data_sampled: ".sol domain names and registration data",
    api_endpoint: "https://naming.bonfida.org",
    sample_frequency: "Every 10 minutes",
    data_points_per_sample: "~2,000-20,000 domains",
    letter_extraction_method: "Extract letters from domain names (excluding .sol suffix)",
    example_data: "alex.sol, blockchain.sol, crypto.sol, defi.sol",
    notes: "Bonfida naming service data"
  },
  {
    id: 4,
    name: "Language.fi Registry",
    category: "Oracle",
    sampling_method: "Internal",
    data_sampled: "Internal primitive registry entries and staking data",
    api_endpoint: "https://api.language.fi",
    sample_frequency: "Every 30 seconds",
    data_points_per_sample: "~20,000-120,000 entries",
    letter_extraction_method: "Extract letters from primitive names and descriptions",
    example_data: "LETTER_A, LETTER_B, SENTENCE_HELLO_WORLD",
    notes: "Primary oracle source for internal protocol data"
  },
  {
    id: 5,
    name: "Gate.io Listings",
    category: "Exchange",
    sampling_method: "API",
    data_sampled: "Exchange token listings, trading pairs, and symbols",
    api_endpoint: "https://api.gate.io",
    sample_frequency: "Every hour",
    data_points_per_sample: "~500-3,000 tokens",
    letter_extraction_method: "Extract letters from token symbols and names",
    example_data: "BTC, ETH, USDT, GT, XRP, ADA, SOL",
    notes: "Gate.io spot market listings"
  },
  {
    id: 6,
    name: "Ethereum Token Names",
    category: "Blockchain",
    sampling_method: "API",
    data_sampled: "ERC-20 token names, symbols, and contract addresses",
    api_endpoint: "https://api.etherscan.io",
    sample_frequency: "Every 5 minutes",
    data_points_per_sample: "~8,000-60,000 tokens",
    letter_extraction_method: "Extract letters from token names and symbols",
    example_data: "USDT, USDC, DAI, WETH, UNI, LINK, AAVE",
    notes: "Etherscan token registry data"
  },
  {
    id: 7,
    name: "Ethereum NFT Collections",
    category: "NFT",
    sampling_method: "API",
    data_sampled: "NFT collection names, contract addresses, and metadata",
    api_endpoint: "https://api.opensea.io",
    sample_frequency: "Every 10 minutes",
    data_points_per_sample: "~15,000-90,000 collections",
    letter_extraction_method: "Extract letters from collection names and symbols",
    example_data: "Bored Ape Yacht Club, CryptoPunks, Azuki, Doodles",
    notes: "OpenSea collection data (limited access)"
  },
  {
    id: 8,
    name: "Ethereum ENS Domains",
    category: "Blockchain",
    sampling_method: "API",
    data_sampled: ".eth domain names and registration data",
    api_endpoint: "https://api.ens.domains",
    sample_frequency: "Every 10 minutes",
    data_points_per_sample: "~3,000-25,000 domains",
    letter_extraction_method: "Extract letters from domain names (excluding .eth suffix)",
    example_data: "vitalik.eth, nick.eth, bradley.eth, ethereum.eth",
    notes: "Ethereum Name Service registry"
  },
  {
    id: 9,
    name: "Binance Token Names",
    category: "Exchange",
    sampling_method: "API",
    data_sampled: "Exchange token listings and trading pairs",
    api_endpoint: "https://api.binance.com",
    sample_frequency: "Every hour",
    data_points_per_sample: "~6,000-45,000 tokens",
    letter_extraction_method: "Extract letters from token symbols and names",
    example_data: "BTC, ETH, BNB, USDT, USDC, SOL, XRP",
    notes: "Binance spot and futures markets"
  },
  {
    id: 10,
    name: "Coinbase Listings",
    category: "Exchange",
    sampling_method: "API",
    data_sampled: "Exchange token listings and trading pairs",
    api_endpoint: "https://api.coinbase.com",
    sample_frequency: "Every hour",
    data_points_per_sample: "~400-2,500 tokens",
    letter_extraction_method: "Extract letters from token symbols and names",
    example_data: "BTC, ETH, USDC, SOL, XRP, ADA, DOGE",
    notes: "Coinbase exchange listings"
  },
  {
    id: 11,
    name: "Kraken Listings",
    category: "Exchange",
    sampling_method: "API",
    data_sampled: "Exchange token listings and trading pairs",
    api_endpoint: "https://api.kraken.com",
    sample_frequency: "Every hour",
    data_points_per_sample: "~300-2,000 tokens",
    letter_extraction_method: "Extract letters from token symbols and names",
    example_data: "XBT, ETH, USDT, SOL, XRP, ADA, DOGE",
    notes: "Kraken exchange listings"
  },
  {
    id: 12,
    name: "OKX Listings",
    category: "Exchange",
    sampling_method: "API",
    data_sampled: "Exchange token listings and trading pairs",
    api_endpoint: "https://www.okx.com/api",
    sample_frequency: "Every hour",
    data_points_per_sample: "~350-2,200 tokens",
    letter_extraction_method: "Extract letters from token symbols and names",
    example_data: "BTC, ETH, USDT, SOL, XRP, ADA, DOGE",
    notes: "OKX exchange listings"
  },
  {
    id: 13,
    name: "Bybit Listings",
    category: "Exchange",
    sampling_method: "API",
    data_sampled: "Exchange token listings and trading pairs",
    api_endpoint: "https://api.bybit.com",
    sample_frequency: "Every hour",
    data_points_per_sample: "~400-2,600 tokens",
    letter_extraction_method: "Extract letters from token symbols and names",
    example_data: "BTC, ETH, USDT, SOL, XRP, ADA, DOGE",
    notes: "Bybit exchange listings"
  },
  {
    id: 14,
    name: "GitHub Repos",
    category: "Dev/Social",
    sampling_method: "API",
    data_sampled: "Repository names, descriptions, and README content",
    api_endpoint: "https://api.github.com",
    sample_frequency: "Every 30 minutes",
    data_points_per_sample: "~12,000-95,000 repos",
    letter_extraction_method: "Extract letters from repo names, descriptions, and README files",
    example_data: "facebook/react, vuejs/vue, tensorflow/tensorflow",
    notes: "Sampled from trending and starred repositories"
  },
  {
    id: 15,
    name: "GitHub README Content",
    category: "Dev/Social",
    sampling_method: "API",
    data_sampled: "README file content from popular repositories",
    api_endpoint: "https://api.github.com",
    sample_frequency: "Every hour",
    data_points_per_sample: "~25,000-180,000 characters",
    letter_extraction_method: "Extract letters from README markdown content",
    example_data: "React is a JavaScript library for building user interfaces",
    notes: "Full text content from README files"
  },
  {
    id: 16,
    name: "NPM Packages",
    category: "Dev/Social",
    sampling_method: "API",
    data_sampled: "Package names, descriptions, and metadata",
    api_endpoint: "https://registry.npmjs.org",
    sample_frequency: "Every hour",
    data_points_per_sample: "~8,000-65,000 packages",
    letter_extraction_method: "Extract letters from package names and descriptions",
    example_data: "react, vue, angular, express, lodash, axios",
    notes: "NPM registry package data"
  },
  {
    id: 17,
    name: "PyPI Packages",
    category: "Dev/Social",
    sampling_method: "API",
    data_sampled: "Package names, descriptions, and metadata",
    api_endpoint: "https://pypi.org/pypi",
    sample_frequency: "Every hour",
    data_points_per_sample: "~5,000-40,000 packages",
    letter_extraction_method: "Extract letters from package names and descriptions",
    example_data: "django, flask, numpy, pandas, requests, tensorflow",
    notes: "Python Package Index data"
  },
  {
    id: 18,
    name: "Crates.io Packages",
    category: "Dev/Social",
    sampling_method: "API",
    data_sampled: "Crate names, descriptions, and metadata",
    api_endpoint: "https://crates.io/api",
    sample_frequency: "Every hour",
    data_points_per_sample: "~2,000-18,000 crates",
    letter_extraction_method: "Extract letters from crate names and descriptions",
    example_data: "serde, tokio, clap, rand, log, anyhow",
    notes: "Rust crate registry data"
  },
  {
    id: 19,
    name: "Docker Hub Images",
    category: "Dev/Social",
    sampling_method: "API",
    data_sampled: "Container image names, descriptions, and tags",
    api_endpoint: "https://hub.docker.com/v2",
    sample_frequency: "Every hour",
    data_points_per_sample: "~4,000-35,000 images",
    letter_extraction_method: "Extract letters from image names and descriptions",
    example_data: "nginx, redis, postgres, node, python, alpine",
    notes: "Docker Hub container registry"
  },
  {
    id: 20,
    name: "Twitter Usernames",
    category: "Social",
    sampling_method: "API",
    data_sampled: "User handles, display names, and bio text",
    api_endpoint: "https://api.twitter.com",
    sample_frequency: "Every 30 minutes",
    data_points_per_sample: "~15,000-120,000 users",
    letter_extraction_method: "Extract letters from usernames and display names",
    example_data: "@elonmusk, @VitalikButerin, @saylor, @naval",
    notes: "Twitter API data (limited access)"
  },
  {
    id: 21,
    name: "Reddit Subreddits",
    category: "Social",
    sampling_method: "API",
    data_sampled: "Subreddit names, descriptions, and post titles",
    api_endpoint: "https://www.reddit.com/dev/api",
    sample_frequency: "Every hour",
    data_points_per_sample: "~3,000-28,000 subreddits",
    letter_extraction_method: "Extract letters from subreddit names and post titles",
    example_data: "r/bitcoin, r/ethereum, r/cryptocurrency, r/defi",
    notes: "Reddit public API data"
  },
  {
    id: 22,
    name: "Medium Articles",
    category: "Social",
    sampling_method: "API",
    data_sampled: "Article titles, tags, and author names",
    api_endpoint: "https://api.medium.com",
    sample_frequency: "Every hour",
    data_points_per_sample: "~5,000-45,000 articles",
    letter_extraction_method: "Extract letters from article titles and tags",
    example_data: "Understanding Blockchain, The Future of DeFi, Web3 Explained",
    notes: "Medium publication data"
  },
  {
    id: 23,
    name: "Wikipedia Pages",
    category: "Reference",
    sampling_method: "API",
    data_sampled: "Page titles, summaries, and content",
    api_endpoint: "https://en.wikipedia.org/w/api.php",
    sample_frequency: "Every 24 hours",
    data_points_per_sample: "~20,000-150,000 pages",
    letter_extraction_method: "Extract letters from page titles and content",
    example_data: "Bitcoin, Ethereum, Blockchain, Cryptocurrency, Decentralization",
    notes: "Wikipedia REST API"
  },
  {
    id: 24,
    name: "DNS Domains",
    category: "Web",
    sampling_method: "API",
    data_sampled: "Domain name records and registration data",
    api_endpoint: "https://api.cloudflare.com",
    sample_frequency: "Every hour",
    data_points_per_sample: "~100,000-800,000 domains",
    letter_extraction_method: "Extract letters from domain names (excluding TLD)",
    example_data: "google.com, facebook.com, amazon.com, apple.com, microsoft.com",
    notes: "Cloudflare DNS data"
  },
  {
    id: 25,
    name: "SSL Certificates",
    category: "Web",
    sampling_method: "API",
    data_sampled: "Certificate names and common names",
    api_endpoint: "https://crt.sh",
    sample_frequency: "Every 24 hours",
    data_points_per_sample: "~50,000-400,000 certificates",
    letter_extraction_method: "Extract letters from certificate common names",
    example_data: "*.google.com, *.facebook.com, *.amazon.com",
    notes: "Certificate transparency log"
  },
  {
    id: 26,
    name: "IPFS Content",
    category: "Storage",
    sampling_method: "API",
    data_sampled: "Content hashes and metadata",
    api_endpoint: "https://api.ipfs.io",
    sample_frequency: "Every hour",
    data_points_per_sample: "~8,000-60,000 hashes",
    letter_extraction_method: "Extract letters from content hash identifiers",
    example_data: "QmX... (CID hashes), IPNS identifiers",
    notes: "IPFS gateway and pinning service data"
  },
  {
    id: 27,
    name: "Arweave Transactions",
    category: "Storage",
    sampling_method: "API",
    data_sampled: "Transaction IDs and metadata tags",
    api_endpoint: "https://arweave.net",
    sample_frequency: "Every hour",
    data_points_per_sample: "~2,000-18,000 transactions",
    letter_extraction_method: "Extract letters from transaction IDs and tags",
    example_data: "Arweave transaction IDs, metadata tags",
    notes: "Arweave blockchain data"
  },
  {
    id: 28,
    name: "NEAR Accounts",
    category: "Blockchain",
    sampling_method: "API",
    data_sampled: "Account names and identifiers",
    api_endpoint: "https://api.near.org",
    sample_frequency: "Every hour",
    data_points_per_sample: "~1,000-12,000 accounts",
    letter_extraction_method: "Extract letters from account names",
    example_data: "alice.near, bob.near, wallet.near",
    notes: "NEAR Protocol account data"
  },
  {
    id: 29,
    name: "Aptos Accounts",
    category: "Blockchain",
    sampling_method: "API",
    data_sampled: "Account addresses and identifiers",
    api_endpoint: "https://api.mainnet.aptoslabs.com",
    sample_frequency: "Every hour",
    data_points_per_sample: "~800-10,000 accounts",
    letter_extraction_method: "Extract letters from account addresses",
    example_data: "Aptos account addresses and resource identifiers",
    notes: "Aptos blockchain data"
  },
  {
    id: 30,
    name: "Sui Accounts",
    category: "Blockchain",
    sampling_method: "API",
    data_sampled: "Account addresses and identifiers",
    api_endpoint: "https://fullnode.mainnet.sui.io",
    sample_frequency: "Every hour",
    data_points_per_sample: "~600-8,000 accounts",
    letter_extraction_method: "Extract letters from account addresses",
    example_data: "Sui account addresses and object identifiers",
    notes: "Sui blockchain data"
  },
  {
    id: 31,
    name: "Cosmos Validators",
    category: "Blockchain",
    sampling_method: "API",
    data_sampled: "Validator names and monikers",
    api_endpoint: "https://cosmos.directory",
    sample_frequency: "Every hour",
    data_points_per_sample: "~500-6,000 validators",
    letter_extraction_method: "Extract letters from validator names and monikers",
    example_data: "Validator monikers and operator addresses",
    notes: "Cosmos ecosystem validator data"
  },
  {
    id: 32,
    name: "Polkadot Parachains",
    category: "Blockchain",
    sampling_method: "API",
    data_sampled: "Parachain names and identifiers",
    api_endpoint: "https://api.polkadot.io",
    sample_frequency: "Every hour",
    data_points_per_sample: "~200-3,000 parachains",
    letter_extraction_method: "Extract letters from parachain names",
    example_data: "Polkadot parachain names and identifiers",
    notes: "Polkadot ecosystem data"
  },
  {
    id: 33,
    name: "Avalanche Subnets",
    category: "Blockchain",
    sampling_method: "API",
    data_sampled: "Subnet names and identifiers",
    api_endpoint: "https://api.avax.network",
    sample_frequency: "Every hour",
    data_points_per_sample: "~300-4,000 subnets",
    letter_extraction_method: "Extract letters from subnet names",
    example_data: "Avalanche subnet names and chain IDs",
    notes: "Avalanche ecosystem data"
  },
  {
    id: 34,
    name: "Grok AI Interactions",
    category: "Social",
    sampling_method: "API",
    data_sampled: "AI conversation data and user prompts",
    api_endpoint: "https://api.x.ai",
    sample_frequency: "Every 30 minutes",
    data_points_per_sample: "~5,000-45,000 interactions",
    letter_extraction_method: "Extract letters from conversation text and prompts",
    example_data: "User prompts, AI responses, conversation threads",
    notes: "Grok AI API data (limited access)"
  },
  {
    id: 35,
    name: "PornHub Video Titles",
    category: "Social",
    sampling_method: "API",
    data_sampled: "Video titles, categories, and tags",
    api_endpoint: "https://api.pornhub.com",
    sample_frequency: "Every hour",
    data_points_per_sample: "~10,000-85,000 videos",
    letter_extraction_method: "Extract letters from video titles and tags",
    example_data: "Video titles, category names, tag labels",
    notes: "Adult content platform data"
  },
];
